env:
  global:
  - secure: B/HPm3tMbgvvF8fryxcTvpH9GtnO5UGJS4QdwbO+Su93xWHYM/RohW0eDpyU6cCpsPOHdBFIQ5sXm7htPqDXpdN8ldbDY1oPC95w0wYh5KfFfHePB37nRrk51/uSJfraHMM4vBbhhqPomqLSKmRXXcm5EJmVUb/GFzj6RPstLZ+nKk97BUc1Yn50HmQfRQXUwBHPR0FZsXAFqLTdmEeYX9HujLBz4TkTSJNe2Z05eRZgWcPEJxhOjbmwCybNkMQEypZVK90FwIqeZbrxK0YUkTY+lFiEJ69wV1q9pXU+5wfGQNBtsG4barokbmzBtGWbXkEtNTOsG+zSqBQ9RhMm08/o+NAJk0mQG2Seb4SFSzrpxiRoCRGe4O6iDRSVvWN11mregMYnrBWi+yi+72Elyt0IjvAaHs3PhX04fTp5X988Dr1Fyi8lIWMyBKN8G/QGlWNuewci8GeGW8nwoptFATmpCmNZeabjvLonQMg12K9IUCUng/xSaCFp5MGHgfk4/4gXras2xN3SYpX7ZL23n9DHMMD74SYaiWWXkilBN86oaGyDw4kE92SuRAixelIS/MOWf+zC1amyCHh32aJwwEzKqd+olRFpcYzgHaW6BgdK9Qk1IqGmSV+MpQTsNnIvt3Fbs7d/6+Kn0wXtluWc+qYmB5bIlrphET39OX6fuTg=
script:
- docker build --target test --tag my-test-image .
- docker run my-test-image ./todo_app/tests/todo_view_model_test.py
- docker run my-test-image ./todo_app/tests/test_client.py
- docker run my-test-image todo_app/tests_e2e -s
